# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    paths:
      - Backend/**

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
   
    - name: Deploy to ec2 server
      uses: appleboy/ssh-action@master
      with:
        host: 18.144.173.138
        username: ubuntu
        key: {{ secrets.SSH_KEY }}
        script: |
          npm install
          node index.js
